// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"OrangeMapshot","status":true,"description":"This plugin will save a picture of the entire map on a Mapshots folder when you press a key. <OrangeMapshot>","parameters":{"useMapName":"true","layerType":"0","drawAutoShadows":"true","drawEvents":"true","keyCode":"44","imageType":"png","imageQuality":"70","imagePath":"./Mapshots"}},
{"name":"morte_efeito","status":true,"description":"Adiciona um efeito de morte nos inimigos na batalha quando eles são derrotados pelo jogador.","parameters":{"Death Animation":"65","Death Sound":"Battle3","Death Volume":"90","Death Pitch":"100","Death Pan":"0","Screen Shake":"true"}},
{"name":"CustomGameOver","status":false,"description":"Remove o ícone de batalha em cima de um inimigo específico na batalha. Adicione a tag <remove_icon> na notas do inimigo para ativar. Exemplo: <remove_icon>.","parameters":{}},
{"name":"skill","status":false,"description":"Plugin de habilidades com janela no menu.","parameters":{}},
{"name":"hudhpinimigo","status":false,"description":"","parameters":{}},
{"name":"ClickableImage","status":true,"description":"","parameters":{}}
];
